Building3D:
  root_dir: 'E:/Building3D/clear data/Entry-level' # Building3D dataset root dir
  num_points: 4096 #2560
  use_color: False #False
  use_intensity: False
  normalize: True
  augment: True
